"""
PROYECTO ATHENA - v0.0.1
Modelos de Base de Datos
Motor de Análisis de Fútbol con IA
"""

from sqlalchemy import (
    Column, Integer, Float, String, Boolean, DateTime,
    ForeignKey, Text, JSON, Enum as SAEnum
)
from sqlalchemy.orm import relationship, declarative_base
from sqlalchemy.sql import func
import enum

Base = declarative_base()

class PosicionEnum(str, enum.Enum):
    PORTERO = "PO"
    LATERAL_DERECHO = "LD"
    CENTRAL_DERECHO = "CD"
    CENTRAL_IZQUIERDO = "CI"
    LATERAL_IZQUIERDO = "LI"
    MEDIOCENTRO_DEFENSIVO = "MCD"
    MEDIOCENTRO = "MC"
    MEDIOCENTRO_OFENSIVO = "MCO"
    EXTREMO_DERECHO = "ED"
    EXTREMO_IZQUIERDO = "EI"
    DELANTERO_CENTRO = "DC"
    SEGUNDO_DELANTERO = "SD"

class PiernaEnum(str, enum.Enum):
    DERECHA = "derecha"
    IZQUIERDA = "izquierda"
    AMBAS = "ambas"

class EstiloOfensivoEnum(str, enum.Enum):
    POSESION = "posesion"
    CONTRAATAQUE = "contraataque"
    DIRECTO = "directo"
    COMBINATIVO = "combinativo"
    PRESION_ALTA = "presion_alta"

class EstiloDefensivoEnum(str, enum.Enum):
    BLOQUE_BAJO = "bloque_bajo"
    BLOQUE_MEDIO = "bloque_medio"
    PRESION_ALTA = "presion_alta"
    ZONA = "zona"
    MIXTA = "mixta"
    HOMBRE_A_HOMBRE = "hombre_a_hombre"

class Liga(Base):
    __tablename__ = "ligas"
    id = Column(Integer, primary_key=True, index=True)
    nombre = Column(String(100), nullable=False)
    pais = Column(String(100), nullable=False)
    nivel = Column(Integer, default=1)
    logo_url = Column(String(500))
    activa = Column(Boolean, default=True)
    temporada_actual = Column(String(20))
    temporada = Column(String(20))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    equipos = relationship("Equipo", back_populates="liga")
    partidos = relationship("Partido", back_populates="liga")

class Equipo(Base):
    __tablename__ = "equipos"
    id = Column(Integer, primary_key=True, index=True)
    nombre = Column(String(150), nullable=False)
    nombre_corto = Column(String(50))
    pais = Column(String(100))
    ciudad = Column(String(100))
    liga_id = Column(Integer, ForeignKey("ligas.id"))
    entrenador = Column(String(150))
    estadio = Column(String(150))
    capacidad_estadio = Column(Integer)
    fundacion = Column(Integer)
    logo_url = Column(String(500))
    formacion_habitual = Column(String(20), default="4-3-3")
    formacion = Column(String(20), default="4-3-3")
    formacion_alternativa = Column(String(20))
    estilo_ofensivo = Column(String(50))
    estilo_ataque = Column(String(50))
    estilo_defensivo = Column(String(50))
    estilo_defensa = Column(String(50))
    nivel_presion = Column(Float, default=5.0)
    juego_aereo = Column(Float, default=5.0)
    juego_bandas = Column(Float, default=5.0)
    juego_banda = Column(Float, default=5.0)
    transiciones_ofensivas = Column(Float, default=5.0)
    transiciones_defensivas = Column(Float, default=5.0)
    transiciones = Column(Float, default=5.0)
    intensidad = Column(Float, default=5.0)
    velocidad_juego = Column(Float, default=5.0)
    velocidad = Column(Float, default=5.0)
    fortaleza_mental = Column(Float, default=5.0)
    agresividad_tactica = Column(Float, default=5.0)
    creatividad = Column(Float, default=5.0)
    disciplina_tactica = Column(Float, default=5.0)
    compacidad_defensiva = Column(Float, default=5.0)
    altura_linea_defensiva = Column(Float, default=5.0)
    pressing_trigger = Column(String(200))
    partidos_jugados = Column(Integer, default=0)
    victorias = Column(Integer, default=0)
    empates = Column(Integer, default=0)
    derrotas = Column(Integer, default=0)
    goles_favor = Column(Integer, default=0)
    goles_contra = Column(Integer, default=0)
    puntos = Column(Integer, default=0)
    victorias_local = Column(Integer, default=0)
    victorias_visitante = Column(Integer, default=0)
    fortaleza_local = Column(Float, default=5.0)
    rendimiento_visitante = Column(Float, default=5.0)
    xg_favor_promedio = Column(Float, default=0.0)
    xg_contra_promedio = Column(Float, default=0.0)
    posesion_promedio = Column(Float, default=50.0)
    tiros_promedio = Column(Float, default=0.0)
    corners_promedio = Column(Float, default=0.0)
    faltas_promedio = Column(Float, default=0.0)
    tarjetas_amarillas_promedio = Column(Float, default=0.0)
    tarjetas_rojas_promedio = Column(Float, default=0.0)
    cambio_sistema_minuto = Column(Integer)
    sistema_segunda_parte = Column(String(20))
    tendencia_goles_primeros = Column(Float, default=0.0)
    tendencia_goles_ultimos = Column(Float, default=0.0)
    reaccion_desventaja = Column(Float, default=5.0)
    gestion_ventaja = Column(Float, default=5.0)
    notas_scout = Column(Text)
    activo = Column(Boolean, default=True)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    liga = relationship("Liga", back_populates="equipos")
    jugadores = relationship("Jugador", back_populates="equipo")
    partidos_local = relationship("Partido", foreign_keys="Partido.equipo_local_id", back_populates="equipo_local")
    partidos_visitante = relationship("Partido", foreign_keys="Partido.equipo_visitante_id", back_populates="equipo_visitante")

class Jugador(Base):
    __tablename__ = "jugadores"
    id = Column(Integer, primary_key=True, index=True)
    nombre = Column(String(150), nullable=False)
    nombre_completo = Column(String(200))
    equipo_id = Column(Integer, ForeignKey("equipos.id"))
    numero_dorsal = Column(Integer)
    posicion_principal = Column(String(10))
    posicion_secundaria = Column(String(10))
    posicion_terciaria = Column(String(10))
    nacionalidad = Column(String(100))
    fecha_nacimiento = Column(String(20))
    edad = Column(Integer)
    pierna_habil = Column(String(20), default="derecha")
    altura = Column(Integer)
    peso = Column(Integer)
    foto_url = Column(String(500))
    valor_mercado = Column(Float)
    velocidad_max = Column(Float, default=50.0)
    velocidad = Column(Float, default=50.0)
    aceleracion = Column(Float, default=50.0)
    resistencia = Column(Float, default=50.0)
    fuerza = Column(Float, default=50.0)
    salto = Column(Float, default=50.0)
    agilidad = Column(Float, default=50.0)
    equilibrio = Column(Float, default=50.0)
    coordinacion = Column(Float, default=50.0)
    potencia = Column(Float, default=50.0)
    distancia_cubierta_promedio = Column(Float)
    sprints_promedio = Column(Float)
    intensidad_fisica = Column(Float, default=50.0)
    pase_corto = Column(Float, default=50.0)
    pase_largo = Column(Float, default=50.0)
    vision = Column(Float, default=50.0)
    control = Column(Float, default=50.0)
    primer_control = Column(Float, default=50.0)
    regate = Column(Float, default=50.0)
    cabeceo = Column(Float, default=50.0)
    remate_pie = Column(Float, default=50.0)
    remate_cabeza = Column(Float, default=50.0)
    potencia_disparo = Column(Float, default=50.0)
    precision_disparo = Column(Float, default=50.0)
    centros = Column(Float, default=50.0)
    centros_precision = Column(Float, default=50.0)
    conduccion = Column(Float, default=50.0)
    pierna_mala = Column(Float, default=50.0)
    tecnica_individual = Column(Float, default=50.0)
    penales = Column(Float, default=50.0)
    tiros_libres = Column(Float, default=50.0)
    corners_tecnica = Column(Float, default=50.0)
    liderazgo = Column(Float, default=50.0)
    concentracion = Column(Float, default=50.0)
    agresividad = Column(Float, default=50.0)
    decision = Column(Float, default=50.0)
    inteligencia_tactica = Column(Float, default=50.0)
    posicionamiento = Column(Float, default=50.0)
    anticipacion = Column(Float, default=50.0)
    creatividad_mental = Column(Float, default=50.0)
    compostura = Column(Float, default=50.0)
    confianza = Column(Float, default=50.0)
    motivacion = Column(Float, default=50.0)
    resiliencia = Column(Float, default=50.0)
    trabajo_equipo = Column(Float, default=50.0)
    presion_tolerancia = Column(Float, default=50.0)
    rendimiento_partidos_grandes = Column(Float, default=50.0)
    entrada = Column(Float, default=50.0)
    marca = Column(Float, default=50.0)
    intercepciones = Column(Float, default=50.0)
    recuperacion_balon = Column(Float, default=50.0)
    cobertura_espacios = Column(Float, default=50.0)
    presion_defensiva = Column(Float, default=50.0)
    duelos_aereos_def = Column(Float, default=50.0)
    bloqueo_tiros = Column(Float, default=50.0)
    lectura_juego_def = Column(Float, default=50.0)
    reflejos = Column(Float, default=50.0)
    posicionamiento_portero = Column(Float, default=50.0)
    salidas = Column(Float, default=50.0)
    manejo = Column(Float, default=50.0)
    saque_con_pie = Column(Float, default=50.0)
    penales_portero = Column(Float, default=50.0)
    comunicacion_portero = Column(Float, default=50.0)
    juego_aereo_portero = Column(Float, default=50.0)
    movimiento_sin_balon = Column(Float, default=50.0)
    desmarques = Column(Float, default=50.0)
    movimiento_entre_lineas = Column(Float, default=50.0)
    amplitud = Column(Float, default=50.0)
    profundidad = Column(Float, default=50.0)
    pressing_activo = Column(Float, default=50.0)
    cobertura_lateral = Column(Float, default=50.0)
    error_primer_control = Column(Float, default=10.0)
    error_bajo_presion = Column(Float, default=10.0)
    error_pierna_mala = Column(Float, default=10.0)
    error_salida_portero = Column(Float, default=10.0)
    error_cobertura = Column(Float, default=10.0)
    error_precision_centros = Column(Float, default=10.0)
    error_definicion = Column(Float, default=10.0)
    amarillas_frecuencia = Column(Float, default=10.0)
    perdidas_posesion = Column(Float, default=10.0)
    fuera_juego_frecuencia = Column(Float, default=10.0)
    partidos_jugados = Column(Integer, default=0)
    partidos_titular = Column(Integer, default=0)
    minutos_jugados = Column(Integer, default=0)
    goles = Column(Integer, default=0)
    asistencias = Column(Integer, default=0)
    xg_total = Column(Float, default=0.0)
    xa_total = Column(Float, default=0.0)
    pases_completados = Column(Integer, default=0)
    pases_intentados = Column(Integer, default=0)
    precision_pases = Column(Float, default=0.0)
    tiros_totales = Column(Integer, default=0)
    tiros_a_puerta = Column(Integer, default=0)
    regates_exitosos = Column(Integer, default=0)
    regates_intentados = Column(Integer, default=0)
    duelos_ganados = Column(Integer, default=0)
    duelos_totales = Column(Integer, default=0)
    intercepciones_stat = Column(Integer, default=0)
    despejes = Column(Integer, default=0)
    tarjetas_amarillas = Column(Integer, default=0)
    tarjetas_rojas = Column(Integer, default=0)
    corners_ganados = Column(Integer, default=0)
    faltas_cometidas = Column(Integer, default=0)
    faltas_recibidas = Column(Integer, default=0)
    rendimiento_local = Column(Float, default=50.0)
    rendimiento_visitante = Column(Float, default=50.0)
    rendimiento_primera_parte = Column(Float, default=50.0)
    rendimiento_segunda_parte = Column(Float, default=50.0)
    rendimiento_ultimos_15min = Column(Float, default=50.0)
    rendimiento_vs_top = Column(Float, default=50.0)
    rendimiento_bajo_lluvia = Column(Float, default=50.0)
    rendimiento_cancha_sintetica = Column(Float, default=50.0)
    caida_rendimiento_cansancio = Column(Float, default=10.0)
    iai_general = Column(Float, default=50.0)
    iai_ofensivo = Column(Float, default=50.0)
    iai_defensivo = Column(Float, default=50.0)
    iai_fisico = Column(Float, default=50.0)
    iai_mental = Column(Float, default=50.0)
    notas_scout = Column(Text)
    activo = Column(Boolean, default=True)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    equipo = relationship("Equipo", back_populates="jugadores")
    actuaciones = relationship("ActuacionJugador", back_populates="jugador")

class Partido(Base):
    __tablename__ = "partidos"
    id = Column(Integer, primary_key=True, index=True)
    liga_id = Column(Integer, ForeignKey("ligas.id"))
    equipo_local_id = Column(Integer, ForeignKey("equipos.id"))
    equipo_visitante_id = Column(Integer, ForeignKey("equipos.id"))
    fecha = Column(DateTime(timezone=True))
    jornada = Column(Integer)
    temporada = Column(String(20))
    estadio = Column(String(150))
    estado = Column(String(30), default="programado")
    api_match_id = Column(String(50), unique=True, nullable=True)
    goles_local = Column(Integer)
    goles_visitante = Column(Integer)
    resultado = Column(String(10))
    jugado = Column(Boolean, default=False)
    posesion_local = Column(Float)
    posesion_visitante = Column(Float)
    tiros_local = Column(Integer, default=0)
    tiros_visitante = Column(Integer, default=0)
    tiros_puerta_local = Column(Integer, default=0)
    tiros_puerta_visitante = Column(Integer, default=0)
    corners_local = Column(Integer, default=0)
    corners_visitante = Column(Integer, default=0)
    faltas_local = Column(Integer, default=0)
    faltas_visitante = Column(Integer, default=0)
    amarillas_local = Column(Integer, default=0)
    amarillas_visitante = Column(Integer, default=0)
    rojas_local = Column(Integer, default=0)
    rojas_visitante = Column(Integer, default=0)
    fuera_juego_local = Column(Integer, default=0)
    fuera_juego_visitante = Column(Integer, default=0)
    xg_local = Column(Float, default=0.0)
    xg_visitante = Column(Float, default=0.0)
    iai_victoria_local = Column(Float)
    iai_empate = Column(Float)
    iai_victoria_visitante = Column(Float)
    iai_mas_25_goles = Column(Float)
    iai_mas_35_goles = Column(Float)
    iai_mas_45_tarjetas = Column(Float)
    iai_mas_95_corners = Column(Float)
    iai_ambos_anotan = Column(Float)
    temperatura = Column(Float)
    clima = Column(String(50))
    arbitro = Column(String(150))
    importancia = Column(String(50))
    liga = relationship("Liga", back_populates="partidos")
    equipo_local = relationship("Equipo", foreign_keys=[equipo_local_id], back_populates="partidos_local")
    equipo_visitante = relationship("Equipo", foreign_keys=[equipo_visitante_id], back_populates="partidos_visitante")
    actuaciones = relationship("ActuacionJugador", back_populates="partido")
    prediccion = relationship("PrediccionIAI", back_populates="partido", uselist=False)

class ActuacionJugador(Base):
    __tablename__ = "actuaciones_jugadores"
    id = Column(Integer, primary_key=True, index=True)
    partido_id = Column(Integer, ForeignKey("partidos.id"))
    jugador_id = Column(Integer, ForeignKey("jugadores.id"))
    minutos_jugados = Column(Integer, default=0)
    titular = Column(Boolean, default=False)
    goles = Column(Integer, default=0)
    asistencias = Column(Integer, default=0)
    amarillas = Column(Integer, default=0)
    rojas = Column(Integer, default=0)
    nota = Column(Float)
    iai_actuacion = Column(Float)
    partido = relationship("Partido", back_populates="actuaciones")
    jugador = relationship("Jugador", back_populates="actuaciones")

class PrediccionIAI(Base):
    __tablename__ = "predicciones_iai"
    id = Column(Integer, primary_key=True, index=True)
    partido_id = Column(Integer, ForeignKey("partidos.id"), unique=True)
    generada_en = Column(DateTime(timezone=True), server_default=func.now())
    version_modelo = Column(String(20), default="0.0.1")
    victoria_local = Column(Float)
    empate = Column(Float)
    victoria_visitante = Column(Float)
    mas_25_goles = Column(Float)
    mas_35_goles = Column(Float)
    ambos_anotan = Column(Float)
    mas_95_corners = Column(Float)
    mas_45_tarjetas = Column(Float)
    confianza_global = Column(Float)
    factores_clave = Column(JSON)
    alertas = Column(JSON)
    notas_analiticas = Column(Text)
    partido = relationship("Partido", back_populates="prediccion")
